### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

# Створення вектора розмірністю 10 з випадковими значеннями (від 0 до 1)
vector = np.random.rand(10)

# Створення матриці 3x3
matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
])

# Виведення вектора
print("Вектор:")
print(vector)
print("Розмір вектора:", vector.shape)

# Виведення матриці
print("\nМатриця:")
print(matrix)
print("Розмір матриці:", matrix.shape)

Вектор:
[0.00142606 0.12102818 0.7967991  0.6704842  0.75344533 0.50485197
 0.77940177 0.74743697 0.5755339  0.23775346]
Розмір вектора: (10,)

Матриця:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
Розмір матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [2]:
vector_plus_10 = np.round(vector + 10, 2)
print("Вектор + 10 (округлений):")
print(vector_plus_10)

Вектор + 10 (округлений):
[10.   10.12 10.8  10.67 10.75 10.5  10.78 10.75 10.58 10.24]


In [3]:
matrix_times_2 = matrix * 2
print("\nМатриця × 2:")
print(matrix_times_2)


Матриця × 2:
[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [4]:
vector_squared = vector ** 2
print("\nВектор у квадраті:")
print(vector_squared)


Вектор у квадраті:
[2.03363606e-06 1.46478201e-02 6.34888805e-01 4.49549064e-01
 5.67679863e-01 2.54875509e-01 6.07467116e-01 5.58662029e-01
 3.31239266e-01 5.65267076e-02]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [5]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [8]:
A = np.array([
    [0.18, 0.53],
    [0.75, 0.47],
    [0.35, 0.21]
])

B = np.array([
    [0.17, 0.58, 0.75],
    [0.38, 0.11, 0.15]
])

C = np.array([[0], [1]])  # 2×1
D = np.array([[0, 1], [1, 0]])  # 2×2

# Множення A · B
result_matrix = np.dot(A, B)  # буде 3×3
print("Результат A · B (3×3):\n", result_matrix)

Результат A · B (3×3):
 [[0.232  0.1627 0.2145]
 [0.3061 0.4867 0.633 ]
 [0.1393 0.2261 0.294 ]]


In [9]:
# Нова матриця A: (2×3), нова B: (3×2)
A2 = np.array([
    [0.2, 0.4, 0.6],
    [0.1, 0.3, 0.5]
])  # 2×3

B2 = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])  # 3×2

# A2 (2×3) · B2 (3×2) → result_matrix (2×2)
result_matrix = np.dot(A2, B2)
print("\nМатричне множення A2 · B2 (2×2):\n", result_matrix)



Матричне множення A2 · B2 (2×2):
 [[4.4 5.6]
 [3.5 4.4]]


In [10]:
result_C = np.dot(result_matrix, C)  # → 2×1
print("\nРезультат result_matrix · C (2×1):\n", result_C)



Результат result_matrix · C (2×1):
 [[5.6]
 [4.4]]


Множення (2×2) × (2×1) → вектор 2×1
Множення (2×2) × (2×2) → матриця 2×2
Матрицю D можна розглядати як оператор перестановки стовпців (swaps columns)



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [12]:
# Створимо вектор 1D
vector = np.random.rand(10)
print("\nОригінальний вектор:\n", vector)
print("Форма вектора:", vector.shape)

# Транспонування — але для 1D numpy-масиву результат не зміниться
vector_T = vector.T
print("Транспонований вектор (1D):\n", vector_T)
print("Форма після транспонування:", vector_T.shape)


Оригінальний вектор:
 [0.91101096 0.39118047 0.89805332 0.80436205 0.84800927 0.42706827
 0.6623547  0.13724233 0.95524646 0.6595607 ]
Форма вектора: (10,)
Транспонований вектор (1D):
 [0.91101096 0.39118047 0.89805332 0.80436205 0.84800927 0.42706827
 0.6623547  0.13724233 0.95524646 0.6595607 ]
Форма після транспонування: (10,)


Спостереження: для одновимірного вектора shape не змінюється при транспонуванні — np.transpose() або .T не впливає на shape, поки вектор не має двох осей.

In [13]:
# Розширення до 2D вектора: колонка (10×1)
column_vector = np.expand_dims(vector, axis=1)
print("\nСтовпцевий вектор (column_vector):\n", column_vector)
print("Форма column_vector:", column_vector.shape)



Стовпцевий вектор (column_vector):
 [[0.91101096]
 [0.39118047]
 [0.89805332]
 [0.80436205]
 [0.84800927]
 [0.42706827]
 [0.6623547 ]
 [0.13724233]
 [0.95524646]
 [0.6595607 ]]
Форма column_vector: (10, 1)


In [14]:
column_vector_T = column_vector.T
print("\nТранспонований стовпцевий вектор:\n", column_vector_T)
print("Форма:", column_vector_T.shape)



Транспонований стовпцевий вектор:
 [[0.91101096 0.39118047 0.89805332 0.80436205 0.84800927 0.42706827
  0.6623547  0.13724233 0.95524646 0.6595607 ]]
Форма: (1, 10)
